### ISSUE TITLE
error text: sh: sshfs: command not found

### ISSUE THREAD

**Issue by HTKT** [dstuecken/sshfs-gui#7] opened 2015-09-10 10:37 UTC
When I mount , i got error text: sh: sshfs: command not found. Anyway to solve it?

thanks

**Comment by dstuecken** [comment] 2015-09-10 11:05
Read the documentation, you need sshfs since this is just a GUI for the command line utility:

You need Mac OS X 10.9+ and at least one of the utilities listed below in order to use the sshfs gui:

sshfs from https://github.com/osxfuse/sshfs/releases / http://osxfuse.github.io/
MacFUSE from https://code.google.com/p/macfuse/
or a custom compiled sshfs from brew, macports, ..
Otherwise this GUI won't function.

**Comment by HTKT** [comment] 2015-09-10 11:46
Thanks. I will install these ultility.
BTW, can you help me to show how to implement sshfs in cocoa app? Thanks much

**Comment by ayspunde** [comment] 2015-09-17 19:16
Same error:sh:     sshfs: command not found

I have sshfs and MacFUSE installed, on cmd:
$ which sshfs
/usr/local/bin/sshfs

Thanks in advance!

**Comment by jleaders** [comment] 2016-06-08 19:39
I get a similar issue:

`sudo port install sshfs-gui`

restart terminal

`sshfs-gui`

`-bash: sshfs-gui: command not found`

**Comment by YuriyNasretdinov** [comment] 2016-08-28 19:02
The problem is probably caused by path being in /usr/local/bin which is not included in the default PATH variable in Mac OS X. So GUI would probably be unable to locate sshfs in this directory. I would suggest adding frequent locations into PATH at application start in the source code by doing somehing like "putenv("PATH=" + getenv("PATH") + ":/usr/local/bin/:/opt/local/bin");"

**Comment by dstuecken** [comment] 2016-08-29 08:24
@jleaders the shfs-gui is not available in port. You should try `sudo port install sshfs` instead. Or alternatively `brew install sshfs` if you use homebrew.

For graphical installations of sshfs you should check out the pages i recommended in my first comment:
> sshfs from https://github.com/osxfuse/sshfs/releases / http://osxfuse.github.io/ MacFUSE from https://code.google.com/p/macfuse/

**Comment by jleaders** [comment] 2016-08-29 23:49
It is available in port for me

    $ port search sshfs-gui

    sshfs-gui @1.3 (fuse)
        OS X GUI for sshfs

**Comment by dstuecken** [comment] 2016-08-30 05:15
Oh, thats seems to be another project.

**Comment by dstuecken** [comment] 2016-09-18 09:51
This should be fixed now. Thanks to @YuriyNasretdinov for your path suggestion.

**Closed by dstuecken** 2016-09-18 09:51 UTC
